server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    tomcat:
      uri-encoding: UTF-8

spring:
  profiles:
    active: dev
    include:
      - env # 在当前目录下新建 application-env.yml 配置敏感信息
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动名称
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      timeout: 3000ms
  web:
    locale: zh_CN
    locale-resolver: fixed

# knife4j配置
springdoc:
  api-docs:
    path: /v3/api-docs   # 这里必须与上面能 200 返回的路径完全一致
  swagger-ui:
    path: /swagger-ui.html
  group-configs:
    - group: default
      packages-to-scan: com.hubu.controller
knife4j:
  enable: true
  setting:
    language: zh-CN
    # 关键：让前端直接拼这个地址
    openapi-url: /v3/api-docs
    swagger-url: /v3/api-docs

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hubu.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      hubu:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间 两小时
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 小程序的jwt配置
    user-secret-key: itcast
    user-ttl: 7200000
    user-token-name: authentication